### ISSUE TITLE
Week 01 作业提交

### ISSUE THREAD

**Issue by aydenwong** [algorithm013/algorithm013#29]
#学号: G20200343100093
#姓名: ayden
#班级: 13期1班1组
#语言: java
#作业链接: https://github.com/aydenwong/algorithm013/tree/master/Week_01/array-linkedlist-stack-queue
#总结链接: https://github.com/aydenwong/algorithm013/tree/master/Week_01/array-linkedlist-stack-queue/README.md

**Comment by RYYAI** [comment]
#学号: G20200343100223
#姓名: yry
#班级: 13期1班3组
#语言: python
#作业链接: https://github.com/RYYAI/algorithm013/tree/master/Week_01
#总结链接:  https://github.com/RYYAI/algorithm013/blob/master/Week_01/README.md
